name: Generate APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Build Web to APK
        uses: lowcarbrob/action-home-app@v1.1
        with:
          app-name: "DoOrdid"
          activity-name: "MainActivity"
          package-name: "com.ilansafeer.doordid"

      - name: Save APK File
        uses: actions/upload-artifact@v4
        with:
          name: Do-Or-did-APK
          path: ./*.apk
